DEFAULT_DAMPING = 1.0
PLAYER_DAMPING = 0.4

PLAYER_FRICTION = 1.0
WALL_FRICTION = 0.7
DYNAMIC_ITEM_FRICTION = 0.6

PLAYER_MOVE_FORCE_ON_GROUND = 8000
PLAYER_MOVE_FORCE_IN_AIR = 500

PLAYER_MASS = 2.0

PLAYER_JUMP_IMPULSE = 1000
BOOSTED_PLAYER_JUMP_IMPULSE = 1500

GRAVITY = 1500

PLAYER_MAX_HORIZONTAL_SPEED = 340
PLAYER_MAX_VERTICAL_SPEED = 1600

TILE_WIDTH = 128
TILE_HEIGHT = TILE_WIDTH
WIDTH = 10 * TILE_WIDTH
HEIGHT = 6 * TILE_HEIGHT
VIEWPORT_MARGIN = 280
TITLE = "Ice Game"


INITIAL_POWER = 5

TIME_PER_POWER_DECREASE = 10