PLAYER_JUMP_SPEED = 12
BOOSTED_PLAYER_JUMP_SPEED = 18

PLAYER_MOVEMENT_SPEED = 4

GRAVITY = 0.7

TILE_WIDTH = 128
TILE_HEIGHT = TILE_WIDTH
WIDTH = 10 * TILE_WIDTH
HEIGHT = 6 * TILE_HEIGHT
VIEWPORT_MARGIN = 280
TITLE = "Ice Game"


INITIAL_POWER = 30

TIME_PER_POWER_DECREASE = 20

MAX_LEVEL = 2
START_LEVEL = 2  # 2 for testing, this should be changed to 1 on release
